<?php
/**
 * Default Status Codes
 **/

const STATUS_CODE_SUCCESS = 200;
const STATUS_CODE_CREATED = 201;
const STATUS_CODE_EMPTY = 204;
const STATUS_CODE_BAD_REQUEST = 400;
const STATUS_CODE_TOO_MANY_REQUESTS = 429;
const STATUS_CODE_UNAUTHORIZED = 401;
const STATUS_CODE_FORBIDDEN = 403;
const STATUS_CODE_NOT_FOUND = 404;
const STATUS_CODE_NOT_SUPPORTED_METHOD = 405;
const STATUS_CODE_INTERNAL_ERROR = 500;
const STATUS_CODE_UNAVAILABLE_SERVER = 503;
const STATUS_CODE_SERVER_TIMEOUT = 504;
const STATUS_CODE_UPGRADE_REQUIRED = 426;
const STATUS_CODE_LOCKED = 423;

